---
# Variables applied to ALL hosts in the inventory.
# These set common Ansible connection parameters.

# Ansible connection settings
ansible_user: ansible
ansible_password: ansible
ansible_become: true
ansible_become_method: enable
ansible_network_os: arista.eos.eos
ansible_connection: ansible.netcommon.httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443

# Place all devices in the MGMT VRF for eAPI/SSH access
ansible_httpapi_use_proxy: false
